---
name: pterodactyl Panel Gameserver - BETA
version: 0.1.26
slug: pterodactyl_panel
image: ghcr.io/ddanii/pterodactyl_panel-{arch}
description: OpenSource Gameserver
url: https://github.com/FaserF/hassio-addons/tree/master/pterodactyl
arch:
  - amd64
services:
  - mysql:need
startup: application
boot: auto
webui: "[PROTO:ssl]://[HOST]:[PORT:80]"
map:
  - share:rw
  - ssl
ingress: true
init: false
panel_icon: mdi:controller
options:
  PUID: 1
  password:
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  PUID: int
  password: password
  ssl: bool
  certfile: str
  keyfile: str
  reset_database: bool?
ports:
  "443": 443
  80/tcp: 80
ports_description:
  80/tcp: Web interface http
  443/tcp: SSL Web interface
