---
name: pterodactyl Panel Gameserver - BETA
version: v1.11.3
slug: pterodactyl_panel
image: ghcr.io/ddanii/pterodactyl_panel-{arch}
description: OpenSource Gameserver
url: https://github.com/DDanii/HA-Add-ons-by-DDanii/tree/master/pterodactyl
arch:
  - amd64
services:
  - mysql:need
map:
  - share:rw
  - ssl
ingress: false
init: false
panel_icon: mdi:controller
options:
  password:
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  ssl: bool
  certfile: str
  keyfile: str
  reset_database: bool?
ports:
  "443": 443
  80/tcp: 80
ports_description:
  80/tcp: Web interface http
  443/tcp: SSL Web interface
