---
name: ViewTube - BETA
version: 0.12.2-rebuild
slug: ViewTube
image: ghcr.io/ddanii/ViewTube-{arch}
description: Alternative YouTube frontend
url: https://github.com/DDanii/HA-Add-ons-by-DDanii/tree/master/ViewTube
arch:
  - amd64
init: false
options:
  VIEWTUBE_REDIS_HOST: 57fef649-redis
  VIEWTUBE_DATABASE_HOST: mongodb
schema:
  VIEWTUBE_REDIS_HOST: str
  VIEWTUBE_DATABASE_HOST: str
ports:
  "8066": 8066
ports_description:
  8066/tcp: Web interface http
